"""Unique constraint for history model

Revision ID: 3fcb772c7bde
Revises: 9b4286219299
Create Date: 2022-02-23 14:43:12.618212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fcb772c7bde'
down_revision = '9b4286219299'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'dota_item_history', ['item_id', 'date'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'dota_item_history', type_='unique')
    # ### end Alembic commands ###
